version: '3'

services:
  google-cloud-web:
    image: nginx:alpine
    container_name: google-cloud-web
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./styles.css:/usr/share/nginx/html/styles.css
    ports:
      - "8080:80"
    command: ["nginx", "-g", "daemon off;"]
    restart: always
